"""create customer_account_ledger_discrepancy table

Revision ID: 7b995588da96
Revises: 0c306ff431c6
Create Date: 2026-08-03 20:09:28.738888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b995588da96"
down_revision: str | Sequence[str] | None = "0c306ff431c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_account_ledger_discrepancy",
        sa.Column(
            "discrepancy_id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("no", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prev_no", sa.BigInteger(), nullable=False),
        sa.Column(
            "expected_balance",
            sa.Numeric(precision=16, scale=2, decimal_return_scale=2),
            nullable=True,
        ),
        sa.Column(
            "actual_balance",
            sa.Numeric(precision=16, scale=2, decimal_return_scale=2),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["customer_account.id"],
        ),
        sa.PrimaryKeyConstraint("discrepancy_id"),
    )
    op.create_index(
        "uq_customer_account_ledger_discrepancy_open",
        "customer_account_ledger_discrepancy",
        ["id"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_customer_account_ledger_discrepancy_open",
        table_name="customer_account_ledger_discrepancy",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_table("customer_account_ledger_discrepancy")
    # ### end Alembic commands ###
